import = [
    "~/.config/alacritty/themes/themes/thelovelace.toml"
]

[env]
TERM = "xterm-256color"

[font.normal]
family = "MesloLGS NF"

[window]
padding = { x = 2, y = 6}
dynamic_padding = true
	
[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[keyboard]
bindings = [
{ key = "N", mods = "Control", action = "CreateNewWindow" }
]

[font] 
size = 13

